# Human Capital Analytics and Reporting Case Study

In [17]:
# Import packages 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
import statsmodels.api as sm
from datetime import date

import warnings
warnings.filterwarnings("ignore")

%matplotlib inline

In [3]:
# Set display options
pd.set_option('display.max_rows', 150)

## Data Analysis

In [4]:
# Read in the data

# Create dataframe variables 
ra = pd.read_csv('Case_Study_HCAR_Research_2019_Recruiting_Activity_Data.csv')    # Recruiting Activity Dataframe
os = pd.read_csv('Case_Study_HCAR_Research_2019_Offer_Status_Data.csv')           # Offer Status Dataframe

In [5]:
# Check the dimensions of the datasets
# Output is in the form (rows, columns)
print(ra.shape)
print('')
print(os.shape)

(4972, 9)

(125, 3)

### Recruiting Activity Dataframe

In [6]:
# Print information on the Recruiting Activity dataset
ra.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4972 entries, 0 to 4971
Data columns (total 9 columns):
Candidate ID Number                  4959 non-null float64
Position Title                       4959 non-null object
Department                           4959 non-null object
Furthest Recruiting Stage Reached    4959 non-null object
Date of Application                  4959 non-null object
Application Source                   4959 non-null object
Highest Degree                       4959 non-null object
Years of Experience                  4959 non-null float64
Candidate Type                       4959 non-null object
dtypes: float64(2), object(7)
memory usage: 349.7+ KB

**There are null values in the dataset because the number of entries in each column doesn't match the total number of entries in the RangeIndex.**

In [7]:
# Check for null values
ra.isna().sum()

Candidate ID Number                  13
Position Title                       13
Department                           13
Furthest Recruiting Stage Reached    13
Date of Application                  13
Application Source                   13
Highest Degree                       13
Years of Experience                  13
Candidate Type                       13
dtype: int64

**There are 13 null values in each column.**

In [9]:
# Filter dataframe for all null values to examine them and determine what should be done with them
ra[ra.isna().any(axis=1)]

,Candidate ID Number,Position Title,Department,Furthest Recruiting Stage Reached,Date of Application,Application Source,Highest Degree,Years of Experience,Candidate Type
4959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

**Since the rows with null values dont contain any information they will be dropped from the dataframe.**

In [10]:
# Drop null values
ra.dropna(inplace=True)

In [11]:
# Check to see if all null values have been dropped
ra.isna().sum().sum()

0

In [16]:
# Analyze all columns except Candidate ID Number and Date of Application to see unique values in each column 
[print(ra[i].unique()) for i in ra.columns.drop(['Candidate ID Number', 'Date of Application'])]

['Associate Software Developer' 'Associate Relationship Manager'
 'Associate Product Manager' 'Finance Manager' 'Operations Coordinator'
 'Business Operations Manager' 'Sr. Business Analyst'
 'Sr. Product Manager' 'IT Analyst' 'Sr. Software Engineer'
 'Sr. Customer Service Operations Associate' 'UX Designer'
 'Financial Analyst' 'Account Executive' 'Operations Generalist']
['Engineering' 'Sales' 'Product' 'Finance' 'Operations' 'IT']
['Offer Sent' 'New Application' 'In-House Interview' 'Phone Screen']
['Campus Job Board' 'Campus Event' 'Advertisement' 'Career Fair' 'Website'
 'Agency' 'Outsourced' 'Internal Referral']
['PhD' 'Masters' 'Bachelors' 'JD' 'Phd']
[ 2.  0.  1.  3.  5.  7.  4. 15.  6. 13.  8. 10. 14. 12. 11.  9.]
['Campus' 'Experienced']

[None, None, None, None, None, None, None]

### Offer Status DataFrame

In [12]:
# Print information on the Offer Status dataset
os.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 3 columns):
Candidate ID Number    125 non-null int64
Offer Date             125 non-null object
Offer Decision         125 non-null object
dtypes: int64(1), object(2)
memory usage: 3.0+ KB

**There are no null values in this dataset.**

In [17]:
pd.merge(left=ra, right=os, how='outer')

,Candidate ID Number,Position Title,Department,Furthest Recruiting Stage Reached,Date of Application,Application Source,Highest Degree,Years of Experience,Candidate Type,Offer Date,Offer Decision
0,2468.0,Associate Software Developer,Engineering,Offer Sent,11/1/18,Campus Job Board,PhD,2.0,Campus,12/15/18,Offer Response Pending
1,2471.0,Associate Relationship Manager,Sales,Offer Sent,12/13/18,Campus Event,Masters,0.0,Campus,1/31/19,Offer Response Pending
2,2475.0,Associate Software Developer,Engineering,Offer Sent,12/21/18,Advertisement,Masters,0.0,Campus,2/5/19,Offer Response Pending
3,2480.0,Associate Relationship Manager,Sales,Offer Sent,12/25/18,Campus Event,Masters,0.0,Campus,2/9/19,Offer Response Pending
4,2486.0,Associate Relationship Manager,Sales,Offer Sent,12/6/18,Campus Event,Masters,1.0,Campus,1/17/19,Offer Response Pending
5,2493.0,Associate Software Developer,Engineering,Offer Sent,12/11/18,Campus Event,PhD,1.0,Campus,1/26/19,Offer Response Pending
6,2501.0,Associate Software Developer,Engineering,Offer Sent,12/13/18,Campus Job Board,Bachelors,0.0,Campus,1/26/19,Offer Response Pending
7,2510.0,Associate Relationship Manager,Sales,Offer Sent,12/13/18,Career Fair,Masters,0.0,Campus,1/28/19,Offer Response Pending
8,2520.0,Associate Software Developer,Engineering,Offer Sent,11/23/18,Career Fair,Bachelors,0.0,Campus,1/5/19,Offer Response Pending
9,2531.0,Associate Software Developer,Engineering,Offer Sent,1/2/19,Campus Event,PhD,1.0,Campus,2/15/19,Offer Response Pending
10,2543.0,Associate Relationship Manager,Sales,Offer Sent,12/26/18,Campus Job Board,Masters,0.0,Campus,2/6/19,Offer Response Pending
11,2556.0,Associate Software Developer,Engineering,Offer Sent,11/10/18,Campus Event,PhD,2.0,Campus,12/28/18,Offer Response Pending
12,2570.0,Associate Software Developer,Engineering,Offer Sent,1/5/16,Advertisement,Bachelors,0.0,Campus,2/14/16,Offer Accepted
13,2585.0,Associate Software Developer,Engineering,Offer Sent,9/9/17,Campus Event,Bachelors,0.0,Campus,10/20/17,Offer Accepted
14,2601.0,Associate Relationship Manager,Sales,Offer Sent,12/12/18,Advertisement,JD,2.0,Campus,1/11/19,Offer Accepted
15,2618.0,Associate Software Developer,Engineering,Offer Sent,12/2/18,Advertisement,Bachelors,0.0,Campus,1/4/19,Offer Accepted
16,2636.0,Associate Relationship Manager,Sales,Offer Sent,11/1/17,Campus Job Board,Masters,0.0,Campus,12/5/17,Offer Accepted
17,2655.0,Associate Software Developer,Engineering,Offer Sent,11/12/17,Career Fair,Bachelors,0.0,Campus,12/17/17,Offer Accepted
18,2675.0,Associate Product Manager,Product,Offer Sent,11/9/16,Campus Job Board,PhD,2.0,Campus,12/8/16,Offer Accepted
19,2696.0,Associate Product Manager,Product,Offer Sent,8/25/18,Campus Event,Bachelors,0.0,Campus,9/27/18,Offer Accepted
20,2718.0,Associate Software Developer,Engineering,Offer Sent,10/2/18,Campus Job Board,PhD,1.0,Campus,10/31/18,Offer Accepted
21,2741.0,Associate Software Developer,Engineering,Offer Sent,8/28/18,Career Fair,Bachelors,0.0,Campus,10/5/18,Offer Accepted
22,2765.0,Associate Relationship Manager,Sales,Offer Sent,10/20/16,Website,Bachelors,0.0,Campus,11/28/16,Offer Accepted
23,2790.0,Associate Software Developer,Engineering,Offer Sent,8/17/18,Campus Event,Bachelors,0.0,Campus,9/19/18,Offer Accepted
24,2816.0,Associate Relationship Manager,Sales,Offer Sent,10/31/18,Website,Bachelors,0.0,Campus,12/11/18,Offer Accepted
25,2843.0,Associate Software Developer,Engineering,Offer Sent,9/13/16,Campus Event,PhD,1.0,Campus,10/16/16,Offer Accepted
26,2871.0,Associate Software Developer,Engineering,Offer Sent,11/13/17,Campus Job Board,Bachelors,0.0,Campus,12/14/17,Offer Accepted
27,2900.0,Associate Software Developer,Engineering,Offer Sent,9/18/16,Campus Event,Bachelors,0.0,Campus,10/26/16,Offer Accepted
28,2930.0,Associate Software Developer,Engineering,Offer Sent,8/3/18,Career Fair,Bachelors,0.0,Campus,9/4/18,Offer Accepted
29,2961.0,Associate Software Developer,Engineering,Offer Sent,10/14/16,Career Fair,Bachelors,0.0,Campus,11/20/16,Offer Accepted
30,2993.0,Associate Software Developer,Engineering,Offer Sent,11/5/18,Website,PhD,2.0,Campus,12/11/18,Offer Accepted
31,3026.0,Associate Software Developer,Engineering,Offer Sent,10/16/16,Career Fair,Masters,0.0,Campus,11/23/16,Offer Accepted
32,3060.0,Associate Relationship Manager,Sales,Offer Sent,9/5/17,Career Fair,Bachelors,0.0,Campus,10/10/17,Offer Accepted
33,3095.0,Associate Product Manager,Product,Offer Sent,8/28/18,Campus Event,Bachelors,0.0,Campus,9/29/18,Offer Accepted
34,3131.0,Associate Software Developer,Engineering,Offer Sent,8/1/18,Career Fair,PhD,2.0,Campus,9/7/18,Offer Accepted
35,3168.0,Associate Relationship Manager,Sales,Offer Sent,8/29/18,Campus Event,Masters,0.0,Campus,10/3/18,Offer Accepted
36,3206.0,Associate Software Developer,Engineering,Offer Sent,9/17/17,Career Fair,Bachelors,0.0,Campus,10/28/17,Offer Accepted
37,3245.0,Associate Relationship Manager,Sales,Offer Sent,12/14/16,Campus Event,Masters,0.0,Campus,1/13/17,Offer Accepted
38,3285.0,Associate Software Developer,Engineering,Offer Sent,12/23/17,Career Fair,Bachelors,0.0,Campus,1/22/18,Offer Accepted
39,3326.0,Associate Software Developer,Engineering,Offer Sent,9/15/18,Career Fair,Bachelors,0.0,Campus,10/16/18,Offer Accepted
40,3368.0,Associate Software Developer,Engineering,Offer Sent,9/23/18,Career Fair,Bachelors,0.0,Campus,10/24/18,Offer Accepted
41,3411.0,Associate Software Developer,Engineering,Offer Sent,1/12/17,Career Fair,Bachelors,0.0,Campus,2/11/17,Offer Accepted
42,3455.0,Associate Software Developer,Engineering,Offer Sent,8/30/18,Campus Event,PhD,1.0,Campus,9/30/18,Offer Accepted
43,3500.0,Associate Relationship Manager,Sales,Offer Sent,9/25/18,Campus Job Board,Bachelors,0.0,Campus,10/27/18,Offer Accepted
44,3546.0,Associate Software Developer,Engineering,Offer Sent,10/26/16,Campus Event,Bachelors,0.0,Campus,1/1/17,Offer Declined
45,3593.0,Associate Software Developer,Engineering,Offer Sent,9/26/18,Campus Event,Bachelors,0.0,Campus,11/17/18,Offer Declined
46,3641.0,Associate Product Manager,Product,Offer Sent,10/7/17,Campus Job Board,PhD,2.0,Campus,12/13/17,Offer Declined
47,3690.0,Associate Relationship Manager,Sales,Offer Sent,8/11/18,Campus Event,Masters,0.0,Campus,10/15/18,Offer Declined
48,3740.0,Associate Software Developer,Engineering,Offer Sent,11/7/16,Campus Event,PhD,3.0,Campus,12/30/16,Offer Declined
49,3791.0,Associate Software Developer,Engineering,Offer Sent,10/3/17,Campus Event,Bachelors,0.0,Campus,11/22/17,Offer Declined
50,3843.0,Associate Relationship Manager,Sales,Offer Sent,10/22/18,Career Fair,Bachelors,0.0,Campus,12/13/18,Offer Declined
51,3896.0,Associate Relationship Manager,Sales,Offer Sent,9/28/16,Campus Event,Masters,1.0,Campus,12/2/16,Offer Declined
52,3950.0,Associate Relationship Manager,Sales,Offer Sent,12/12/16,Career Fair,Bachelors,0.0,Campus,2/15/17,Offer Declined
53,4005.0,Associate Software Developer,Engineering,Offer Sent,11/24/16,Campus Job Board,Bachelors,0.0,Campus,1/9/17,Offer Declined
54,4061.0,Associate Software Developer,Engineering,Offer Sent,11/28/18,Website,Bachelors,0.0,Campus,1/15/19,Offer Declined
55,4118.0,Associate Software Developer,Engineering,Offer Sent,10/16/18,Website,PhD,1.0,Campus,12/6/18,Offer Declined
56,4176.0,Associate Software Developer,Engineering,Offer Sent,10/2/18,Career Fair,Bachelors,0.0,Campus,11/29/18,Offer Declined
57,4235.0,Associate Software Developer,Engineering,Offer Sent,10/7/18,Campus Job Board,Masters,1.0,Campus,12/8/18,Offer Declined
58,4295.0,Associate Product Manager,Product,Offer Sent,10/8/18,Career Fair,PhD,2.0,Campus,11/30/18,Offer Declined
59,4356.0,Associate Software Developer,Engineering,Offer Sent,12/1/18,Website,Bachelors,0.0,Campus,1/31/19,Offer Declined
60,4418.0,Associate Software Developer,Engineering,Offer Sent,12/14/16,Website,Bachelors,0.0,Campus,2/19/17,Offer Declined
61,4481.0,Finance Manager,Finance,Offer Sent,8/15/18,Website,Masters,5.0,Experienced,10/11/18,Offer Declined
62,4545.0,Associate Software Developer,Engineering,Offer Sent,9/14/18,Campus Event,Bachelors,0.0,Campus,11/4/18,Offer Declined
63,4610.0,Associate Software Developer,Engineering,Offer Sent,1/1/16,Campus Job Board,Bachelors,0.0,Campus,2/22/16,Offer Declined
64,4676.0,Associate Product Manager,Product,Offer Sent,10/9/16,Campus Job Board,PhD,1.0,Campus,12/8/16,Offer Declined
65,4743.0,Associate Relationship Manager,Sales,Offer Sent,9/11/18,Campus Event,Masters,0.0,Campus,11/4/18,Offer Declined
66,4811.0,Associate Product Manager,Product,Offer Sent,9/20/17,Campus Job Board,Bachelors,0.0,Campus,11/8/17,Offer Declined
67,4880.0,Associate Product Manager,Product,Offer Sent,9/4/18,Campus Event,PhD,2.0,Campus,11/5/18,Offer Declined
68,4950.0,Associate Relationship Manager,Sales,Offer Sent,9/17/17,Campus Event,Masters,0.0,Campus,11/16/17,Offer Declined
69,5021.0,Associate Software Developer,Engineering,Offer Sent,10/30/17,Campus Event,Bachelors,0.0,Campus,12/22/17,Offer Declined
70,5093.0,Associate Software Developer,Engineering,Offer Sent,10/27/17,Career Fair,Bachelors,0.0,Campus,12/18/17,Offer Declined
71,5166.0,Associate Software Developer,Engineering,New Application,9/14/16,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
72,5240.0,Associate Software Developer,Engineering,New Application,1/4/16,Advertisement,Bachelors,0.0,Campus,NaN,NaN
73,5315.0,Associate Software Developer,Engineering,New Application,9/25/17,Advertisement,Bachelors,0.0,Campus,NaN,NaN
74,5391.0,Associate Software Developer,Engineering,New Application,3/20/16,Advertisement,Bachelors,0.0,Campus,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
4898,6332756.0,Associate Product Manager,Product,Phone Screen,3/29/17,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4899,6333477.0,Associate Software Developer,Engineering,Phone Screen,9/10/17,Campus Job Board,PhD,2.0,Campus,NaN,NaN
4900,6334199.0,Business Operations Manager,Operations,Phone Screen,4/20/16,Career Fair,Masters,8.0,Experienced,NaN,NaN
4901,6334922.0,Business Operations Manager,Operations,Phone Screen,7/18/16,Agency,Masters,4.0,Experienced,NaN,NaN
4902,6335646.0,Business Operations Manager,Operations,Phone Screen,9/8/18,Agency,PhD,8.0,Experienced,NaN,NaN
4903,6336371.0,Associate Relationship Manager,Sales,Phone Screen,12/28/17,Campus Job Board,Masters,0.0,Campus,NaN,NaN
4904,6337097.0,Associate Relationship Manager,Sales,Phone Screen,10/27/18,Campus Job Board,Masters,2.0,Campus,NaN,NaN
4905,6337824.0,Associate Relationship Manager,Sales,Phone Screen,11/10/16,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4906,6338552.0,Associate Software Developer,Engineering,Phone Screen,8/20/18,Campus Event,PhD,1.0,Campus,NaN,NaN
4907,6339281.0,Associate Relationship Manager,Sales,Phone Screen,10/16/16,Campus Job Board,PhD,4.0,Campus,NaN,NaN
4908,6340011.0,Associate Software Developer,Engineering,Phone Screen,8/8/18,Campus Event,PhD,1.0,Campus,NaN,NaN
4909,6340742.0,Associate Relationship Manager,Sales,Phone Screen,1/31/17,Campus Job Board,Masters,0.0,Campus,NaN,NaN
4910,6341474.0,Finance Manager,Finance,Phone Screen,1/9/16,Internal Referral,Masters,6.0,Experienced,NaN,NaN
4911,6342207.0,Associate Software Developer,Engineering,Phone Screen,10/7/18,Campus Job Board,PhD,4.0,Campus,NaN,NaN
4912,6342941.0,Associate Relationship Manager,Sales,Phone Screen,10/25/18,Website,Bachelors,0.0,Campus,NaN,NaN
4913,6343676.0,Associate Relationship Manager,Sales,Phone Screen,2/17/18,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4914,6344412.0,Associate Software Developer,Engineering,Phone Screen,12/20/18,Campus Job Board,PhD,2.0,Campus,NaN,NaN
4915,6345149.0,Sr. Product Manager,Product,Phone Screen,1/4/18,Website,Bachelors,7.0,Experienced,NaN,NaN
4916,6345887.0,Associate Product Manager,Product,Phone Screen,11/24/17,Campus Job Board,PhD,2.0,Campus,NaN,NaN
4917,6346626.0,Business Operations Manager,Operations,Phone Screen,4/21/16,Website,Bachelors,8.0,Experienced,NaN,NaN
4918,6347366.0,Associate Relationship Manager,Sales,Phone Screen,11/16/17,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4919,6348107.0,Associate Relationship Manager,Sales,Phone Screen,12/20/17,Campus Job Board,Masters,2.0,Campus,NaN,NaN
4920,6348849.0,Associate Software Developer,Engineering,Phone Screen,1/24/16,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4921,6349592.0,Associate Software Developer,Engineering,Phone Screen,10/14/18,Advertisement,PhD,4.0,Campus,NaN,NaN
4922,6350336.0,Associate Software Developer,Engineering,Phone Screen,12/13/16,Website,PhD,1.0,Campus,NaN,NaN
4923,6351081.0,Associate Software Developer,Engineering,Phone Screen,3/4/17,Website,Bachelors,0.0,Campus,NaN,NaN
4924,6351827.0,Associate Software Developer,Engineering,Phone Screen,11/14/18,Campus Event,PhD,2.0,Campus,NaN,NaN
4925,6352574.0,Associate Software Developer,Engineering,Phone Screen,12/29/18,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4926,6353322.0,Associate Relationship Manager,Sales,Phone Screen,2/23/17,Campus Job Board,JD,0.0,Campus,NaN,NaN
4927,6354071.0,Associate Software Developer,Engineering,Phone Screen,10/14/18,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4928,6354821.0,Associate Product Manager,Product,Phone Screen,9/2/17,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4929,6355572.0,Associate Product Manager,Product,Phone Screen,12/18/16,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4930,6356324.0,Operations Coordinator,Operations,Phone Screen,10/9/17,Advertisement,PhD,1.0,Campus,NaN,NaN
4931,6357077.0,Associate Relationship Manager,Sales,Phone Screen,9/5/18,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4932,6357831.0,Associate Relationship Manager,Sales,Phone Screen,11/24/17,Campus Event,Masters,1.0,Campus,NaN,NaN
4933,6358586.0,Associate Relationship Manager,Sales,Phone Screen,2/21/18,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4934,6359342.0,Associate Product Manager,Product,Phone Screen,9/25/16,Campus Event,PhD,4.0,Campus,NaN,NaN
4935,6360099.0,Associate Software Developer,Engineering,Phone Screen,9/23/18,Website,Bachelors,0.0,Campus,NaN,NaN
4936,6360857.0,Associate Software Developer,Engineering,Phone Screen,10/15/16,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4937,6361616.0,Sr. Customer Service Operations Associate,Operations,Phone Screen,7/25/17,Outsourced,Masters,14.0,Experienced,NaN,NaN
4938,6362376.0,Associate Software Developer,Engineering,Phone Screen,8/11/18,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4939,6363137.0,Associate Software Developer,Engineering,Phone Screen,3/13/17,Campus Job Board,PhD,2.0,Campus,NaN,NaN
4940,6363899.0,UX Designer,Product,Phone Screen,8/20/17,Agency,Bachelors,5.0,Experienced,NaN,NaN
4941,6364662.0,Associate Relationship Manager,Sales,Phone Screen,12/10/16,Campus Job Board,Masters,1.0,Campus,NaN,NaN
4942,6365426.0,Associate Product Manager,Product,Phone Screen,9/11/17,Website,Bachelors,0.0,Campus,NaN,NaN
4943,6366191.0,IT Analyst,IT,Phone Screen,8/9/17,Advertisement,PhD,4.0,Campus,NaN,NaN
4944,6366957.0,Associate Software Developer,Engineering,Phone Screen,2/5/16,Advertisement,PhD,0.0,Campus,NaN,NaN
4945,6367724.0,Associate Relationship Manager,Sales,Phone Screen,10/7/18,Campus Job Board,Masters,2.0,Campus,NaN,NaN
4946,6368492.0,Associate Software Developer,Engineering,Phone Screen,10/31/17,Website,PhD,1.0,Campus,NaN,NaN
4947,6369261.0,Associate Software Developer,Engineering,Phone Screen,9/26/18,Career Fair,Bachelors,0.0,Campus,NaN,NaN
4948,6370031.0,Sr. Product Manager,Product,Phone Screen,2/5/17,Agency,Bachelors,5.0,Experienced,NaN,NaN
4949,6370802.0,Associate Relationship Manager,Sales,Phone Screen,11/12/18,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4950,6371574.0,Associate Software Developer,Engineering,Phone Screen,9/2/17,Campus Event,PhD,0.0,Campus,NaN,NaN
4951,6372347.0,Associate Relationship Manager,Sales,Phone Screen,12/26/18,Website,JD,0.0,Campus,NaN,NaN
4952,6373121.0,Associate Product Manager,Product,Phone Screen,12/20/16,Campus Job Board,Bachelors,0.0,Campus,NaN,NaN
4953,6373896.0,Business Operations Manager,Operations,Phone Screen,11/15/16,Agency,Masters,4.0,Experienced,NaN,NaN
4954,6374672.0,Associate Software Developer,Engineering,Phone Screen,11/6/16,Campus Event,PhD,3.0,Campus,NaN,NaN
4955,6375449.0,Associate Software Developer,Engineering,Phone Screen,1/17/18,Advertisement,PhD,2.0,Campus,NaN,NaN
4956,6376227.0,Associate Relationship Manager,Sales,Phone Screen,10/7/16,Campus Job Board,Masters,0.0,Campus,NaN,NaN
4957,6377006.0,Associate Software Developer,Engineering,Phone Screen,3/19/17,Campus Job Board,PhD,0.0,Campus,NaN,NaN
4958,6377786.0,Associate Software Developer,Engineering,Phone Screen,10/1/17,Campus Job Board,PhD,0.0,Campus,NaN,NaN
4959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4960,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4961,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4962,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4964,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4965,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4966,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4969,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4972,21031.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11/15/16,Offer Accepted